spring:
  application:
    name: tempoapp
  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 1
  cache:
    caches:
      analysisCache:
        caffeine:
          spec: expireAfterWrite=1h
      conversationCache:
        caffeine:
          spec: expireAfterWrite=30m
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/tempo}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: ${PORT:8080}

security:
  jwt:
    secret-key: ${SECURITY_JWT_SECRET_KEY}
    expiration-time: 3600000

springdoc:
  swagger-ui:
    path: /swagger-ui

api:
  openaq:
    url: https://api.openaq.org
    key: ${API_OPENAQ_KEY}

prediction:
  service:
    base-url: http://localhost:5000


cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}