spring:
  application:
    name: tempoapp
  ai:
    openai:
      api-key: ${OPENAI-API-KEY}
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 1
  cache:
    caches:
      analysisCache:
        caffeine:
          spec: expireAfterWrite=1h
      conversationCache:
        caffeine:
          spec: expireAfterWrite=30m


springdoc:
  swagger-ui:
    path: /swagger-ui

api:
  openaq:
    url: https://api.openaq.org
    key: ${OPENAQ-API-KEY}

