spring:
  application:
    name: tempoapp
  ai:
    openai:
      api-key: ${OPENAI-KEY}
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 1

  cache:
    cache-names: analysisCache
    caffeine:
      spec: expireAfterWrite=1h

springdoc:
  swagger-ui:
    path: /swagger-ui

api:
  openaq:
    url: https://api.openaq.org
    key: c8b27cfee48f95653149806366add1b06f9598693bfc293fdaf5d77d0ea80eba

